#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=capitaine-cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=com.github.vinceliuice.McMojave
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kdeglobals KScreen ScaleFactor ''
kdeglobals_kscreen_scalefactor=''
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors=''
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
